---
#Training
 batch_size: 30
 epochs: 1
 rnnBinSize: 2
 smoothInputs: 1
 cvPart: 'HeldOutBlocks'
 outputDelay: 50
 directionality: 'unidirectional'
 loss: crossentropy
 learning_rate: 0.0001
 learning_rate_decay: 0.1
 learning_rate_decay_step: 100 #Set it to a very large number to prevent this to be used
 dropout: 0.2
 var_dropout_s: 0
 var_dropout_t: 0
 zoneout: False
 weight_decay: 0.1
 noisy_threshold: 0

# Data augmentation
 constantOffsetSD: 0.6
 randomWalkSD: 0.02
 whiteNoiseSD: 0.02
 train_val_timeSteps: 1200
 test_timeSteps: 7500

# Network
 batchnorm: 'tdBN'
 neuron_count: 256
 use_bias: True
 steps: 10
 warmup_steps: 2
 network_type: 'default'
 reset_by_subtraction: True
 surrogate_gradient: 'square'
 init_u: 'zero'

#Neuron
 Vth: 0.4
 Vth_init_range: 0.1
 Vth_trainable: False

 tau: 0.6 # also mean of distribution if tau_init_range > 0
 tau_init_range: 0.1 # width of uniform distribution / std of normal distribution
 tau_init_distribution: 'uniform' # options are 'uniform' and 'normal'
 tau_trainable: True
 tau_sigmoid: False

 constrain_method: 'forward'
 reset_by_subtraction: True
 surrogate_gradient: 'square'
 init_u: 'zero'


#Dataset
 output_type: 'vel'
 
# Quantization
#  static_quantisation: False
#  quantize_weight: 4 #False or bitcount (4,8,16)
#  quantize_bias: 6
#  quantize_accumulation: False #only used if weights are quantized
#  quantize_activation: False #tau quantisation
#  quantize_membrane_pot: False #membrane potential bitwidth and quantisation
#  quantize_input: 8
#  quantize_input_scaling: 3
 static_quantisation: False
 quantize_weight: False #False or bitcount (4,8,16)
 quantize_bias: False
 quantize_accumulation: False #only used if weights are quantized
 quantize_activation: False #tau quantisation
 quantize_membrane_pot: False #membrane potential bitwidth and quantisation
 quantize_input: False
 quantize_input_scaling: False
 quantisation_scaling: 'max' #'max' or 'mean' for 2.5*mean scaling


 rpr_start_fraction: 0.9
 rpr_step_epochs: 3

#Reporting
 experiment_name: 'baseline_fp_run'
 loss_steps: 100 #how often to report the loss
 output_report: Report.txt
 output_plots: ./
 output_csv: ./
 results_dir: ./
 if_plot: False

#General
 seed: 'random' #use 'random' for a non-deterministic seed
 device: cuda:0
 trials: 1
 5-fold: False
 early_stopping: False
 dataset_file: 
#save and load model
 save_model: False
 save_model_dir: ./
 load_model: False 
 load_model_dir: 